### ISSUE TITLE
provide an example of a working SAL and (failing) test invocation against example.com

### ISSUE THREAD

**Issue by gobengo** [steve-bate/activitypub-testsuite#5]
I evaluated this to see if I could figure out how to use it. cloning, poetry install, invoking pytest all worked as expected, but then I got a test report with no tests run.

Then I got to this https://github.com/steve-bate/activitypub-testsuite/blob/main/docs/installation.md#create-a-server-test-project
<img width="984" alt="Screenshot 2023-09-25 at 5 56 35 PM" src="https://github.com/steve-bate/activitypub-testsuite/assets/171782/b3c4d323-6dd2-44ed-b78f-49b69b94a813">

It seems like I need to make a SAL in order to run against a remote URL. Is there an example of that anywhere?
If not, no worries. I could read more code to figure it out.

**Comment by steve-bate** [comment]
Hi Ben. There are three existing server extension projects listed at the top of the README.md (activitypub-express, onepage.pub, and bovine). The onepage.pub project may be a good one to use as an example. The server SALs are in separate repositories (linked from the README.me). It's not trivial to create a SAL so I was waiting to add more extensive documentation until I determined the interest level in this style of testing. 

I'm currently working on a cookiecutter template to make it easier to create the scaffolding for a new server project. 

If you'd like, I could give some ideas about how to support your scenario. One of the first steps in creating a SAL is determining how the server will be run, accessed, and reset between tests (for proper test isolation). The current server projects are starting the servers in a subprocess and the server is reset for each each test. The server reset uses a test-specific HTTP route that's been added without modifying the original server code. That technique may not be possible depending on the implementation of the server. For the existing servers, this technique allows the server process to be started only once for the test session so that the tests run reasonably fast (15-45 seconds).

**Comment by gobengo** [comment]
> There are three existing server extension projects listed at the top of the README.md (activitypub-express, onepage.pub, and bovine)

Thanks for pointing this out. Sorry I missed it before

**Comment by gobengo** [comment]
I was able to follow the README over here and get a report. Great! Thanks again for the pointer @steve-bate 
https://github.com/steve-bate/apex-aptesting

Sample report: https://bafybeia6bzetwmjngw4laf64fcnqiobhw2g5shbpg2rfrnxr2ylbxwrkhy.ipfs.w3s.link/bengo-test-report.html
